id: PB82464AA
initial_creation_type: input
source_metadata:
  title: Kachöpa Series
  language: de
  description: Prayers and Practices
  volume:
    90a187e8ca254026ae9d461fd1593d33:
      title: Raising the Windhorse
      parent: Prayers and Practices
created_at: '2022-03-01T00:09:28.225778'
last_modified_at: '2022-03-01T00:09:28.225781'
